/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  //侧边栏配置
  tutorialSidebar1: [
    {
      type: 'category',
      label: '算法',
      collapsed: false,
      link: {
        type: "generated-index",
        title: "算法"
      },
      items: [
        //列表
        {
          type: 'category',
          label: 'leetcode算法集',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "leetcode算法集"
          },
          items: [
            //列表
            'algorithm/leetcode/hot100_1',
            'algorithm/leetcode/hot100_2',
          ]
        },
        {
          type: 'category',
          label: '常见算法',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "常见算法"
          },
          items: [
            //列表
            'algorithm/common/binaryTree',
            'algorithm/common/linkedlist',
            'algorithm/common/map',
            'algorithm/common/dp',
            'algorithm/common/greedy',
            'algorithm/common/recursion',
            'algorithm/common/sort',
            'algorithm/common/binarySearch',
            'algorithm/common/slidingWindow',
            'algorithm/common/monotonicStack',
            'algorithm/common/disjoint'

          ]
        },
        //其他算法
        'algorithm/jianzhi', 
      ]
    }
  ],
  tutorialSidebar2: [
    {
      type: 'category',
      label: '后端',
      collapsed: false,
      link: {
        type: "generated-index",
        title: "后端"
      },
      items: [
        //列表
        {
          type: 'category',
          label: 'Java',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "Java"
          },
          items: [
            //列表
            'backend/java/JDK8_CompletableFuture',
            'backend/java/Stream',
            'backend/java/MimeType',
            'backend/java/ConcurrentLimit'   
          ]
        },
        {
          type: 'category',
          label: 'Git',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "Git"
          },
          items: [
            //列表
            'backend/git/GitOperateInProject', 
          ]
        },
        {
          type: 'category',
          label: '框架',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "框架"
          },
          items: [
            //列表
            'backend/framework/Jenkins', 
            'backend/framework/Okhttp3',
            'backend/framework/Flyway',
            'backend/framework/Logback',
            'backend/framework/Shiro',
            'backend/framework/Nginx'
          ]
        },
        {
          type: 'category',
          label: 'Kubernetes',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "Kubernetes"
          },
          items: [
            //列表
            'backend/kubernetes/K8S_Install', 
            'backend/kubernetes/Helm3', 
          ]
        },
        {
          type: 'category',
          label: 'Docker',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "Docker"
          },
          items: [
            //列表
            'backend/docker/Docker01'
          ]
        },
        {
          type: 'category',
          label: '数据库',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "数据库"
          },
          items: [
            //列表
            'backend/database/MysqlEncode',
            'backend/database/PostgreSql_ASCII_SQL'
          ]
        }
      ]
    }
  ],
  tutorialSidebar3: [
    {
      type: 'category',
      label: '前端',
      collapsed: false,
      link: {
        type: "generated-index",
        title: "前端"
      },
      items: [
        //列表
        {
          type: 'category',
          label: '面试',
          collapsed: false,
          link: {
            type: "generated-index",
            title: "面试"
          },
          items: [
            //列表
            'frontend/review/review'
          ]
        }
      ]
    }
  ],
  tutorialSidebar4: [
    {
      type: 'category',
      label: '计算机网络',
      collapsed: false,
      link: {
        type: "generated-index",
        title: "计算机网络"
      },
      items: [
        //列表
        'computer_network/cn',
        'computer_network/iptables'
      ]
    }
  ],
  tutorialSidebar5: [
    {
      type: 'category',
      label: '设计模式',
      collapsed: false,
      link: {
        type: "generated-index",
        title: "设计模式"
      },
      items: [
        //列表
        'design_pattern/dp_review'
      ]
    }
  ],
  tutorialSidebar6: [
    {
      type: 'category',
      label: 'Mac',
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Mac"
      },
      items: [
        //列表
        'mac/Mac01',
        'mac/Mac02',
        'mac/OhMyAsh'
      ]
    }
  ],
  
};

module.exports = sidebars;
